/* eslint-disable max-len */
export const labels = {
  app_title: 'MinhaSaúde',
  vaccine_card: 'Vacinas e Medicamentos',
  vaccine_card_description: 'Confira seu passaporte completo de vacinas e lista de medicamentos. Você pode adicionar novos medicamentos a qualquer momento.',
  exams_card: 'Exames e Consultas',
  exams_card_description: 'Tenha acesso a todos os seus exames e histórico de consultas de forma rápida e segura. Aqui você também pode marcar a sua próxima consulta.',
  edu_card: 'Educativo',
  edu_card_description: 'Aqui você encontra informações sobre doenças, vacinas, medicamentos e muito mais. Tudo para você ficar por dentro do mundo da saúde.',
  increase_font: 'Aumentar fonte',
  decrease_font: 'Diminuir fonte',
  reset_font: 'Redefinir fonte',
  delete_item: 'Excluir item',
  medicines: 'Medicamentos',
  add_medicine: 'Adicionar Medicamento',
  vaccines: 'Vacinas',
  add: 'Adicionar',
  medicine_name: 'Medicamento:',
  medicine_frequency: 'Frequência:',
  medicine_frequency_placeholder: 'Ex: 2x por dia, 1x por semana...',
  medicine_duration: 'Duração:',
  medicine_duration_placeholder: 'Ex: Até 30/12/2021, Uso contínuo...',
  exam_results: 'Resultados de Exames',
  exam_result_downloaded: 'Resultado de exame baixado com sucesso!',
  scheduled_appointment: 'Consultas Agendadas',
  schedule_appointment: 'Agendar Consulta',
  schedule: 'Agendar',
  specialty: 'Especialidade:',
  date: 'Data:',
  close: 'Fechar'
}
